# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 05:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_commentlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='manual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='manuals.Manual'),
        ),
    ]
