# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lang',
            field=models.CharField(choices=[('English', 'en'), ('Русский', 'ru')], default=('English', 'en'), max_length=2),
        ),
    ]
