# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 05:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manuals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='manual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='manuals.Manual'),
        ),
    ]
