# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuals', '0002_topic_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manual',
            name='meta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
