# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuals', '0003_auto_20171027_1141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step',
            old_name='index',
            new_name='order',
        ),
        migrations.AlterField(
            model_name='step',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
