# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 09:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manuals', '0004_auto_20171027_1149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manual',
            options={},
        ),
        migrations.RenameField(
            model_name='manual',
            old_name='updated',
            new_name='modified',
        ),
        migrations.RemoveField(
            model_name='manual',
            name='meta',
        ),
        migrations.AddField(
            model_name='manual',
            name='content',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manual',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='manual',
            name='tags',
            field=models.ManyToManyField(to='manuals.Tag'),
        ),
    ]
