# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 09:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manuals', '0007_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='manual',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='manuals.Manual'),
            preserve_default=False,
        ),
    ]
