# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 10:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manuals', '0009_userrate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step',
            old_name='body',
            new_name='content',
        ),
    ]
