# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manuals', '0010_auto_20171027_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='StepAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manuals.Manual')),
            ],
        ),
    ]
