# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 13:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manuals', '0011_stepattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stepattachment',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manuals.Step'),
        ),
    ]
