# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuals', '0013_auto_20171027_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='manual',
            name='cover',
            field=models.URLField(default='https://semantic-ui.com/images/wireframe/image.png'),
        ),
    ]
