# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 10:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firstmanualbadge',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='tenthmanualbadge',
            name='icon',
        ),
    ]
