# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 11:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0002_auto_20171025_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firstmanualbadge',
            name='display',
        ),
    ]
